name: Nuget

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
  workflow_dispatch:
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
        
    - name: Restore dependencies
      run: nuget restore $SOLUTION
    
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    
  build:
    needs:
    - test
    env:
      BUILD_CONFIG: 'Release'
      SOLUTION: 'Steganography-Library.sln'
      
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5

    - name: Restore dependencies
      run: nuget restore $SOLUTION

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Build
      run: dotnet build $SOLUTION --configuration $BUILD_CONFIG --no-restore /p:Version=1.1.$GITHUB_RUN_NUMBER

    - name: Publish
      if: startsWith(github.ref, 'refs/heads/master')
      run: nuget push **\*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_API_KEY}}
